# This is a basic workflow to help you get started with Actions

name: Lint & Format

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  golangci:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Setup environment variables
        run: |
          echo "$(pwd)/bin" >> $GITHUB_PATH
          echo "GOPATH=$(pwd)" >> $GITHUB_ENV
          
      - name: Check code formatting
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: ./src
          gofmt-flags: -l -d
          
      - name: Install dependencies
        run: |
          go get github.com/go-ini/ini
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega/...
        
      - name: golangci-lint surfstore
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          working-directory: src/surfstore
